# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20180724_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-pub_date']},
        ),
    ]
