# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20180727_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Creator',
            new_name='creator',
        ),
    ]
